# Generated by Django 6.0.1 on 2026-01-31 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='daily_time',
            field=models.PositiveIntegerField(help_text='Minutos disponíveis por dia'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.PositiveSmallIntegerField(help_text='1 = baixa | 5 = alta')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='studies.studyplan')),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='0 = Segunda | 6 = Domingo')),
                ('duration', models.PositiveIntegerField(help_text='Minutos')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='studies.studyplan')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.subject')),
            ],
        ),
    ]
