# Generated by Django 6.0.1 on 2026-02-15 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_studyplan_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='title',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='1 = Fácil | 5 = Muito Difícil'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='1 = Muito Baixa | 5 = Muito Alta'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='study_days',
            field=models.JSONField(default=list, help_text='Lista de dias da semana (Segunda, Terça, etc)'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='subjects',
            field=models.JSONField(default=list, help_text='Lista de matérias'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='daily_time',
            field=models.FloatField(help_text='Tempo diário em horas'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_details', to='studies.studyplan'),
        ),
    ]
