# Generated by Django 6.0.1 on 2026-02-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_alter_studyplan_options_remove_studyplan_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='subject_difficulties',
            field=models.JSONField(blank=True, default=list, help_text="Lista de matérias com dificuldades: [{name: 'Mat', difficulty: 4}, ...]"),
        ),
    ]
