# Generated by Django 6.0.1 on 2026-02-16 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_studyplan_subject_difficulties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studysession',
            options={'ordering': ['day_of_week', 'order']},
        ),
        migrations.AddField(
            model_name='studysession',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ordem de estudo do dia (1a, 2a, 3a matéria)'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='question_list',
            field=models.TextField(blank=True, default='', help_text='Lista de questões sugeridas para o dia'),
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='0 = Segunda | 6 = Domingo')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='studies.studyplan')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('plan', 'date')},
            },
        ),
    ]
