# Generated by Django 6.0.2 on 2026-02-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_alter_studysession_options_studysession_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='duration',
            field=models.FloatField(help_text='Minutos (pode ser fracionado)'),
        ),
    ]
